In [5]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets, layers, models, callbacks
from tensorflow.keras.datasets import mnist


In [6]:
import numpy as np
import struct
import matplotlib.pyplot as plt
 
filename = 'train-labels-idx1-ubyte'
binfile = open(filename , 'rb')
buf = binfile.read()
 
index = 0
magic, numLabel = struct.unpack_from('>II' , buf , index)
print(magic,numLabel)
index += struct.calcsize('>II')

for ii in range(10000):
    label = struct.unpack_from('>1B' ,buf, index)
    index += struct.calcsize('>1B')
    if ii == 0:
        y_train = np.array(list(label))
    else:
        y_train = np.vstack([y_train,label])
binfile.close()

filename = 'train-images-idx3-ubyte'
binfile = open(filename , 'rb')
buf = binfile.read()
 
index = 0
magic, numImages , numRows , numColumns = struct.unpack_from('>IIII' , buf , index)
print(magic,numImages,numRows,numColumns)
index += struct.calcsize('>IIII')

for ii in range(10000):
    im = struct.unpack_from('>784B' ,buf, index)
    index += struct.calcsize('>784B')
    if ii == 0:
        x_train = np.array(list(im))
    else:
        x_train = np.vstack([x_train,im])
binfile.close()
filename = 't10k-labels-idx1-ubyte'
binfile = open(filename , 'rb')
buf = binfile.read()
 
index = 0
magic, numLabel = struct.unpack_from('>II' , buf , index)
print(magic,numLabel)
index += struct.calcsize('>II')

for ii in range(5000):
    label = struct.unpack_from('>1B' ,buf, index)
    index += struct.calcsize('>1B')
    if ii == 0:
        y_test = np.array(list(label))
    else:
        y_test = np.vstack([y_test,label])
binfile.close()

filename = 't10k-images-idx3-ubyte'
binfile = open(filename , 'rb')
buf = binfile.read()
 
index = 0
magic, numImages , numRows , numColumns = struct.unpack_from('>IIII' , buf , index)
print(magic,numImages,numRows,numColumns)
index += struct.calcsize('>IIII')

for ii in range(5000):
    im = struct.unpack_from('>784B' ,buf, index)
    index += struct.calcsize('>784B')
    if ii == 0:
        x_test = np.array(list(im))
    else:
        x_test = np.vstack([x_test,im])
binfile.close()

2049 60000
2051 60000 28 28
2049 10000
2051 10000 28 28


In [19]:
x_train.shape

(10000, 784)

In [20]:
from keras import layers
model = models.Sequential([
    layers.Dense(512,activation='relu',input_shape= (784,)),
    layers.Dropout(0.2),
    layers.Dense(10,activation='softmax')
])
model.compile(optimizer='adam',metrics=['accuracy'],loss='sparse_categorical_crossentropy')

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 512)               401920    
_________________________________________________________________
dropout (Dropout)            (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


In [10]:
def evaluate(target_model):
    _,acc = target_model.evaluate(x_test,y_test)
    return acc

# Save Checkpoints

In [28]:
import os
checkpoint_path = "CheckPoints/cp-{epoch:04d}.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)
print(os.path.dirname(checkpoint_path))
cp_callback = callbacks.ModelCheckpoint(checkpoint_path,verbose=1,save_weights_only=True,save_freq= 10)

CheckPoints


In [14]:
model.save_weights(checkpoint_path.format(epoch=0))

In [21]:
model.fit(x_train,y_train,epochs=50,callbacks=[cp_callback],validation_data=(x_test,y_test),verbose=0)

 model to CheckPoints/cp-0039.ckpt

Epoch 00039: saving model to CheckPoints/cp-0039.ckpt

Epoch 00039: saving model to CheckPoints/cp-0039.ckpt

Epoch 00039: saving model to CheckPoints/cp-0039.ckpt

Epoch 00039: saving model to CheckPoints/cp-0039.ckpt

Epoch 00039: saving model to CheckPoints/cp-0039.ckpt

Epoch 00039: saving model to CheckPoints/cp-0039.ckpt

Epoch 00039: saving model to CheckPoints/cp-0039.ckpt

Epoch 00039: saving model to CheckPoints/cp-0039.ckpt

Epoch 00039: saving model to CheckPoints/cp-0039.ckpt

Epoch 00039: saving model to CheckPoints/cp-0039.ckpt

Epoch 00039: saving model to CheckPoints/cp-0039.ckpt

Epoch 00039: saving model to CheckPoints/cp-0039.ckpt

Epoch 00039: saving model to CheckPoints/cp-0039.ckpt

Epoch 00039: saving model to CheckPoints/cp-0039.ckpt

Epoch 00039: saving model to CheckPoints/cp-0039.ckpt

Epoch 00039: saving model to CheckPoints/cp-0039.ckpt

Epoch 00039: saving model to CheckPoints/cp-0039.ckpt

Epoch 00039: saving model to 

In [25]:
model.weights

[<tf.Variable 'dense_4/kernel:0' shape=(784, 512) dtype=float32, numpy=
 array([[-0.06112225, -0.04991626,  0.0638985 , ..., -0.05200978,
          0.04860543,  0.05558617],
        [-0.02373032,  0.04674341, -0.01070252, ..., -0.02393224,
          0.02293156,  0.05734757],
        [-0.01554946, -0.00721699, -0.01305792, ..., -0.03048572,
          0.02599899,  0.03565741],
        ...,
        [ 0.06432995,  0.05064917,  0.01892324, ...,  0.06158799,
         -0.01781737, -0.018666  ],
        [ 0.04309671,  0.00369897, -0.01067887, ..., -0.04879709,
          0.02248716, -0.00259392],
        [-0.01979022,  0.05032884,  0.01102728, ..., -0.00672696,
         -0.05731683,  0.02007256]], dtype=float32)>,
 <tf.Variable 'dense_4/bias:0' shape=(512,) dtype=float32, numpy=
 array([-0.01741302,  0.05524104, -0.0172956 , -0.00976468, -0.00351338,
        -0.06363378,  0.00309112, -0.0124237 , -0.09735736, -0.02648429,
        -0.04262289,  0.0101248 , -0.03623094, -0.05316623, -0.04658864,


In [29]:
latest = tf.train.latest_checkpoint(checkpoint_dir)
model2 = models.Sequential([
    layers.Dense(512,activation='relu',input_shape= (784,)),
    layers.Dropout(0.2),
    layers.Dense(10,activation='softmax')
])
model2.compile(optimizer='adam',metrics=['accuracy'],loss='sparse_categorical_crossentropy')

In [26]:
model2.weights

[<tf.Variable 'dense_6/kernel:0' shape=(784, 512) dtype=float32, numpy=
 array([[-0.06065919,  0.02844039,  0.00487544, ...,  0.02208591,
          0.06722806, -0.01211688],
        [-0.0521929 , -0.04524567,  0.04971918, ...,  0.00252265,
         -0.01917165,  0.06283465],
        [-0.00174695,  0.01990955, -0.02675221, ...,  0.05291025,
          0.03889732,  0.04520942],
        ...,
        [ 0.02700689,  0.06649047,  0.02579041, ..., -0.01639818,
         -0.00590718, -0.04234947],
        [ 0.01937632,  0.00381311, -0.03251495, ...,  0.02723697,
         -0.06545412,  0.02881331],
        [-0.03398974, -0.0310384 ,  0.06666264, ...,  0.02719057,
         -0.06660717,  0.03081127]], dtype=float32)>,
 <tf.Variable 'dense_6/bias:0' shape=(512,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [30]:
model2.load_weights(latest)

In [31]:
model2.weights

[<tf.Variable 'dense_8/kernel:0' shape=(784, 512) dtype=float32, numpy=
 array([[-0.06112225, -0.04991626,  0.0638985 , ..., -0.05200978,
          0.04860543,  0.05558617],
        [-0.02373032,  0.04674341, -0.01070252, ..., -0.02393224,
          0.02293156,  0.05734757],
        [-0.01554946, -0.00721699, -0.01305792, ..., -0.03048572,
          0.02599899,  0.03565741],
        ...,
        [ 0.06432995,  0.05064917,  0.01892324, ...,  0.06158799,
         -0.01781737, -0.018666  ],
        [ 0.04309671,  0.00369897, -0.01067887, ..., -0.04879709,
          0.02248716, -0.00259392],
        [-0.01979022,  0.05032884,  0.01102728, ..., -0.00672696,
         -0.05731683,  0.02007256]], dtype=float32)>,
 <tf.Variable 'dense_8/bias:0' shape=(512,) dtype=float32, numpy=
 array([-0.01741302,  0.05510779, -0.0172956 , -0.00976468, -0.00344585,
        -0.06363378,  0.00309287, -0.0124237 , -0.09747936, -0.02648429,
        -0.04262289,  0.0101248 , -0.03623094, -0.05316623, -0.04658864,


In [32]:
evaluate(model)

157/157 [==============================] - 0s 694us/step - loss: 2.4931 - accuracy: 0.9330


0.9330000281333923

In [33]:
evaluate(model2)

157/157 [==============================] - 0s 736us/step - loss: 2.5727 - accuracy: 0.9306


0.9305999875068665

In [34]:
model2.save_weights('./manuelCP')

In [35]:
model3 = models.Sequential([
    layers.Dense(512,activation='relu',input_shape= (784,)),
    layers.Dropout(0.2),
    layers.Dense(10,activation='softmax')
])
model3.compile(optimizer='adam',metrics=['accuracy'],loss='sparse_categorical_crossentropy')

In [36]:
model3.load_weights('./manuelCP')

In [37]:
evaluate(model3)

157/157 [==============================] - 0s 705us/step - loss: 2.5727 - accuracy: 0.9306


0.9305999875068665

# Save model
1) model.save   HDF5

In [38]:
 model3.save('model3.h5')

In [39]:
model4= models.load_model('model3.h5')

In [40]:
evaluate(model4)

157/157 [==============================] - 0s 815us/step - loss: 2.5727 - accuracy: 0.9306


0.9305999875068665

In [41]:
import time
saved_model_path = "./saved_models/{}".format(int(time.time()))

In [42]:
model3.save('/tmp/model')


Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: /tmp/model/assets


In [43]:
model3.save('./model')


INFO:tensorflow:Assets written to: ./model/assets


In [44]:
model5 = keras.models.load_model('./model')

In [45]:
evaluate(model5)

157/157 [==============================] - 0s 688us/step - loss: 2.5727 - accuracy: 0.9306


0.9305999875068665